services:
  bot:
    container_name: alphie-bot
    build: ./bot
    env_file:
      - bot.env
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    container_name: alphie-db
    hostname: ${DB_HOSTNAME} # Defined in .env
    build: ./db
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/postgresql/data # Persistent data storage
    ports:
      - ${DB_PORT}:5432