services:
  nginx:
    container_name: alphie-nginx
    build: ./nginx
    env_file:
     - env/.env
     - env/www.env
    volumes:
     - ./cdn/data:${CDN_ROOT}
    ports:
      - "80:80"

  bot:
    container_name: alphie-bot
    build: ./bot
    env_file:
      - env/.env
      - env/bot.s.env
      - env/db.s.env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  db:
    container_name: alphie-db
    hostname: ${DB_HOSTNAME} # Defined in .env
    build: ./db
    env_file:
      - env/.env
      - env/db.s.env
    volumes:
      - ./db/data:/var/lib/postgresql/data # Persistent data storage
    
  cdn:
    container_name: alphie-cdn
    hostname: ${CDN_HOSTNAME} # Defined in .env
    build: ./cdn
    env_file:
     - env/.env
    volumes:
     - ./cdn/data:${CDN_ROOT}
  
  www:
    container_name: alphie-www
    hostname: ${WWW_HOSTNAME} # Defined in .env
    build: ./www
    init: true
    env_file:
     - env/.env
     - env/www.env
     - env/www.s.env
    volumes:
     - ./www/build:/app/sync
    # Syncing the volume and starting nodemon for hot reloading
    command: sh -c "
      rm -rf /app/run && 
      rm -rf /app/sync/* && 
      cp -r /app/build/* /app/sync && 
      ln -s /app/sync /app/run && 
      python3 checkEnv.py && 
      yarn global add nodemon && 
      nodemon --watch /app/sync /app/run/build/index.js"

  grpc:
    container_name: alphie-grpc
    hostname: ${GRPC_HOSTNAME} # Defined in .env
    build: ./rpc
    env_file:
     - env/.env
     - env/db.s.env
     - env/grpc.env
     - env/grpc.s.env